# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.__version__

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [5]:
# Method 1
np.random.random((2,3,5))


array([[[0.22750369, 0.96267735, 0.26518808, 0.70424625, 0.3777862 ],
        [0.53205517, 0.20874638, 0.97898594, 0.15737383, 0.16897728],
        [0.3387975 , 0.77406322, 0.45873956, 0.45753064, 0.06514784]],

       [[0.88681849, 0.34210727, 0.83157756, 0.74500449, 0.95533955],
        [0.79363084, 0.9018415 , 0.36894461, 0.85400066, 0.9171142 ],
        [0.63902782, 0.35411417, 0.70130698, 0.7744567 , 0.19542072]]])

In [10]:
# Method 2
#np.random.random(30) - created the 30 randoom numbers
np.random.random(30).reshape(2,3,5)

array([[[0.98788427, 0.08719126, 0.68704315, 0.6586794 , 0.97593067],
        [0.33181914, 0.33579561, 0.66927062, 0.69635367, 0.00660361],
        [0.28944599, 0.18859683, 0.57531588, 0.36320095, 0.89618746]],

       [[0.11133668, 0.67207877, 0.33818762, 0.9041635 , 0.91952128],
        [0.97397331, 0.1016939 , 0.58183832, 0.87413514, 0.34253268],
        [0.67138696, 0.64498147, 0.10474594, 0.23327759, 0.71738345]]])

In [13]:
# Method 3- normal distributed random values
np.random.normal(size=(2,3,5))

array([[[ 1.33620664, -1.23192134, -2.33263831,  0.92050516,
         -0.28866148],
        [-0.44077471,  0.9602994 , -0.51478769, -0.47106202,
          0.10478649],
        [-0.13945275,  0.14140636,  0.90147861, -0.90353157,
          0.08568206]],

       [[ 0.6918059 , -1.12421846,  0.62649211,  0.28824173,
          1.2498652 ],
        [-0.56224493,  0.15628838, -0.61266062, -0.56279899,
          0.71640519],
        [ 0.83289134,  0.40070186,  2.05676593,  0.10305699,
         -0.78852984]]])

In [15]:
# Method 4- exponencial distributed random values

np.random.exponential(size=(2,3,5))

array([[[0.19557074, 0.02668572, 0.99864953, 0.46894797, 0.58962393],
        [0.08190003, 0.90809834, 0.16337938, 0.99393229, 0.95139136],
        [0.53877138, 0.65840393, 1.82897082, 1.47829808, 0.18314826]],

       [[0.21688582, 4.85833523, 2.13731654, 1.17566418, 1.65735373],
        [1.51359364, 1.16642423, 1.11919823, 0.72130052, 0.71423418],
        [0.17109436, 0.04726215, 2.17670542, 2.27665121, 0.72173109]]])

In [18]:
# Method 4- random integers
#from 0 till 9, with the specified dimensions

np.random.randint(0,10,(2,3,5))

array([[[3, 0, 8, 5, 6],
        [2, 5, 7, 3, 9],
        [4, 1, 7, 5, 4]],

       [[0, 4, 7, 2, 2],
        [2, 7, 3, 1, 5],
        [6, 5, 8, 8, 4]]])

#### 4. Print *a*.


In [37]:
a = np.random.random((2,3,5))
print(a)
type(a)

[[[0.44077822 0.61675757 0.66982973 0.71507157 0.02421088]
  [0.66726527 0.58365032 0.67289862 0.95002218 0.40757541]
  [0.46775884 0.10742855 0.10797262 0.79892289 0.57614666]]

 [[0.42665158 0.25335644 0.14431964 0.60645473 0.68174248]
  [0.2078575  0.32016683 0.64020122 0.65113408 0.88829554]
  [0.41673739 0.56259789 0.65407738 0.7819657  0.35233679]]]


numpy.ndarray

#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [24]:
b=np.full(30,1).reshape(5,3,2)
type(b)

numpy.ndarray

#### 6. Print *b*.


In [25]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [50]:
a.shape == b.shape #They don´t have the same size

False

In [51]:
print(b.shape)
print(a.shape)

(5, 3, 2)
(2, 3, 5)


In [47]:
#I treat it as a list of list
len_ax =len(a)
for y in a:
    len_ay=len(y)
    for z in y:
        len_az= len(z)
        
print(f" x dimension: {len_ax}, y dimension: {len_ay} ,z dimension: {len_az}")

 x dimension: 2, y dimension: 3 ,z dimension: 5


In [52]:
#I treat it as a list of list
len_bx =len(b)
for y in b:
    len_by=len(y)
    for z in y:
        len_bz= len(z)
        
print(f" x dimension: {len_bx}, y dimension: {len_by} ,z dimension: {len_bz}")

 x dimension: 5, y dimension: 3 ,z dimension: 2


In [54]:
if len_ax==len_bx and len_ay==len_by and len_az==len_bz:
    print ("They have the same size")
else:
    print("They don't have the same size")

They don't have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [56]:
ab= a + b
#It can not be added because they have different size
#ValueError: operands could not be broadcast 
#together with shapes (2,3,5) (5,3,2) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [60]:
c= b.transpose()

In [61]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [64]:
d = a+c
print(d)

[[[1.44077822 1.61675757 1.66982973 1.71507157 1.02421088]
  [1.66726527 1.58365032 1.67289862 1.95002218 1.40757541]
  [1.46775884 1.10742855 1.10797262 1.79892289 1.57614666]]

 [[1.42665158 1.25335644 1.14431964 1.60645473 1.68174248]
  [1.2078575  1.32016683 1.64020122 1.65113408 1.88829554]
  [1.41673739 1.56259789 1.65407738 1.7819657  1.35233679]]]


In [69]:
a.shape ==c.shape

True

In [71]:
#It can also be add with:

d =np.add(a,c)
print(d)

[[[1.44077822 1.61675757 1.66982973 1.71507157 1.02421088]
  [1.66726527 1.58365032 1.67289862 1.95002218 1.40757541]
  [1.46775884 1.10742855 1.10797262 1.79892289 1.57614666]]

 [[1.42665158 1.25335644 1.14431964 1.60645473 1.68174248]
  [1.2078575  1.32016683 1.64020122 1.65113408 1.88829554]
  [1.41673739 1.56259789 1.65407738 1.7819657  1.35233679]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [66]:
print(a)

[[[0.44077822 0.61675757 0.66982973 0.71507157 0.02421088]
  [0.66726527 0.58365032 0.67289862 0.95002218 0.40757541]
  [0.46775884 0.10742855 0.10797262 0.79892289 0.57614666]]

 [[0.42665158 0.25335644 0.14431964 0.60645473 0.68174248]
  [0.2078575  0.32016683 0.64020122 0.65113408 0.88829554]
  [0.41673739 0.56259789 0.65407738 0.7819657  0.35233679]]]


In [68]:
print(d)

[[[1.44077822 1.61675757 1.66982973 1.71507157 1.02421088]
  [1.66726527 1.58365032 1.67289862 1.95002218 1.40757541]
  [1.46775884 1.10742855 1.10797262 1.79892289 1.57614666]]

 [[1.42665158 1.25335644 1.14431964 1.60645473 1.68174248]
  [1.2078575  1.32016683 1.64020122 1.65113408 1.88829554]
  [1.41673739 1.56259789 1.65407738 1.7819657  1.35233679]]]


In [ ]:
#The addition is made element by element, like in a matrix addition

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [74]:
e = a*c
print(e)

#or 
#np.multiply(a,c)

[[[0.44077822 0.61675757 0.66982973 0.71507157 0.02421088]
  [0.66726527 0.58365032 0.67289862 0.95002218 0.40757541]
  [0.46775884 0.10742855 0.10797262 0.79892289 0.57614666]]

 [[0.42665158 0.25335644 0.14431964 0.60645473 0.68174248]
  [0.2078575  0.32016683 0.64020122 0.65113408 0.88829554]
  [0.41673739 0.56259789 0.65407738 0.7819657  0.35233679]]]


array([[[0.44077822, 0.61675757, 0.66982973, 0.71507157, 0.02421088],
        [0.66726527, 0.58365032, 0.67289862, 0.95002218, 0.40757541],
        [0.46775884, 0.10742855, 0.10797262, 0.79892289, 0.57614666]],

       [[0.42665158, 0.25335644, 0.14431964, 0.60645473, 0.68174248],
        [0.2078575 , 0.32016683, 0.64020122, 0.65113408, 0.88829554],
        [0.41673739, 0.56259789, 0.65407738, 0.7819657 , 0.35233679]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [75]:
e==a
#It equals because b is a matrix of 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
d_max =np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"Maximum value in d: {d_max}, Minimum  value in d: {d_min}, Mean of all values from d: {d_mean}")

Maximum value in d: 1.9500221830483102, Minimum  value in d: 1.024210879952983, Mean of al value from d: 1.5131394834586467


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [84]:
shape_d =d.shape

In [86]:
f= np.zeros(30).reshape(shape_d)
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [93]:
def percentiles(x,x_min,x_max,d_mean):
    if x > x_min and x < x_mean:
        y = 25
    if x > x_mean and x < x_max:
        y = 75
    if x == x_mean:
        y = 50
    if x == x_min:
        y = 0
    if x == x_max:
        y = 100
    return y

In [100]:
for sub in range(d.shape[0]):
    print(sub)

0
1


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here