# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [5]:
np.random.randint(0,1, size=(2, 3, 5))

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [6]:
np.empty((2, 3, 5))

array([[[1.09310968e-311, 9.73309322e-322, 0.00000000e+000,
         0.00000000e+000, 1.09282783e-311],
        [5.02034658e+175, 7.31556603e+169, 2.23146866e+180,
         6.87297755e-038, 6.12118444e+169],
        [7.43069717e-144, 1.12855837e+277, 6.32672840e+180,
         2.66371964e+233, 5.04621361e+180]],

       [[8.37170571e-144, 3.80985069e+180, 9.30537467e+199,
         8.37901765e+165, 1.43471205e-051],
        [8.00521254e+169, 5.35080953e-038, 4.30620998e-096,
         8.37170584e-144, 6.80774353e-091],
        [3.22241147e-057, 7.26787541e-043, 5.74020278e+180,
         8.37174974e-144, 6.81693983e-310]]])

In [7]:
np.random.randn(2, 3, 5)

array([[[-0.31921218,  0.20726487,  0.60017502,  0.68771134,
          0.98987253],
        [-0.86751064, -0.85516534, -0.32203546,  0.53374117,
          1.83046796],
        [-0.64399754,  0.26864081, -0.68997218, -0.81168099,
         -1.05989974]],

       [[-0.28336001, -1.45076701, -0.45589225,  0.13068211,
         -0.25591694],
        [-1.24409286,  1.41070743, -1.1263126 ,  0.14997188,
          1.43707009],
        [ 0.80952289, -1.03953789, -0.96132597,  0.07209332,
         -1.00270784]]])

In [49]:
a = np.random.rand(3, 2, 5)
print(a)

[[[0.30359978 0.24545779 0.41491716 0.40584203 0.95602968]
  [0.08448142 0.62466835 0.81075975 0.02188641 0.55388527]]

 [[0.02066276 0.66616803 0.24716398 0.63266224 0.86779775]
  [0.69970805 0.392821   0.92968533 0.23390818 0.03111999]]

 [[0.93142177 0.81427188 0.82833313 0.20968327 0.33328278]
  [0.04059322 0.82791842 0.86945209 0.74014243 0.94639682]]]


#### 4. Print *a*.


In [51]:
np.random.rand(3, 2, 5)

array([[[0.75715147, 0.182547  , 0.20762404, 0.76409263, 0.99943756],
        [0.65620109, 0.49278365, 0.64337225, 0.77016201, 0.96196898]],

       [[0.40891941, 0.50648047, 0.34428514, 0.8951902 , 0.02182777],
        [0.79696723, 0.64862764, 0.23400407, 0.78583157, 0.77394854]],

       [[0.66280479, 0.32700074, 0.95110689, 0.72838072, 0.57844283],
        [0.68451719, 0.37044677, 0.93891004, 0.29979602, 0.95077515]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [52]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [53]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [54]:
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
addition = a + b
print(addition)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [18]:
np.add(a, b)
#The arrays have different sizes and therefore can't be added 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [55]:
c = np.transpose(b)
c
#If you use transpose it does NOT become 2,3,5 but actually 3,2,5
#The question is not correct I guess?

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [56]:
d = a + c
d
#It works because I changed the shape of both input arrays to the same size/shape

array([[[1.30359978, 1.24545779, 1.41491716, 1.40584203, 1.95602968],
        [1.08448142, 1.62466835, 1.81075975, 1.02188641, 1.55388527]],

       [[1.02066276, 1.66616803, 1.24716398, 1.63266224, 1.86779775],
        [1.69970805, 1.392821  , 1.92968533, 1.23390818, 1.03111999]],

       [[1.93142177, 1.81427188, 1.82833313, 1.20968327, 1.33328278],
        [1.04059322, 1.82791842, 1.86945209, 1.74014243, 1.94639682]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [57]:
a

array([[[0.30359978, 0.24545779, 0.41491716, 0.40584203, 0.95602968],
        [0.08448142, 0.62466835, 0.81075975, 0.02188641, 0.55388527]],

       [[0.02066276, 0.66616803, 0.24716398, 0.63266224, 0.86779775],
        [0.69970805, 0.392821  , 0.92968533, 0.23390818, 0.03111999]],

       [[0.93142177, 0.81427188, 0.82833313, 0.20968327, 0.33328278],
        [0.04059322, 0.82791842, 0.86945209, 0.74014243, 0.94639682]]])

In [58]:
d

array([[[1.30359978, 1.24545779, 1.41491716, 1.40584203, 1.95602968],
        [1.08448142, 1.62466835, 1.81075975, 1.02188641, 1.55388527]],

       [[1.02066276, 1.66616803, 1.24716398, 1.63266224, 1.86779775],
        [1.69970805, 1.392821  , 1.92968533, 1.23390818, 1.03111999]],

       [[1.93142177, 1.81427188, 1.82833313, 1.20968327, 1.33328278],
        [1.04059322, 1.82791842, 1.86945209, 1.74014243, 1.94639682]]])

In [ ]:
#d = a + 1 (since c = 1)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
e = a * c
e

array([[[0.30359978, 0.24545779, 0.41491716, 0.40584203, 0.95602968],
        [0.08448142, 0.62466835, 0.81075975, 0.02188641, 0.55388527]],

       [[0.02066276, 0.66616803, 0.24716398, 0.63266224, 0.86779775],
        [0.69970805, 0.392821  , 0.92968533, 0.23390818, 0.03111999]],

       [[0.93142177, 0.81427188, 0.82833313, 0.20968327, 0.33328278],
        [0.04059322, 0.82791842, 0.86945209, 0.74014243, 0.94639682]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [61]:
if a.all() == e.all():
    print(True)
else:
    print(False)
    
#They are equal, but I don't exactly understand why? It removed the 1 again

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [62]:
d_max = np.max(d)
d_max

1.9560296781863373

In [63]:
d_min = np.min(d)
d_min

1.0206627566584063

In [67]:
d_mean = np.mean(d)
d_mean

1.5228240250720082

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [98]:
f = np.empty([3,2,5])
f

array([[[0.30359978, 0.24545779, 0.41491716, 0.40584203, 0.95602968],
        [0.08448142, 0.62466835, 0.81075975, 0.02188641, 0.55388527]],

       [[0.02066276, 0.66616803, 0.24716398, 0.63266224, 0.86779775],
        [0.69970805, 0.392821  , 0.92968533, 0.23390818, 0.03111999]],

       [[0.93142177, 0.81427188, 0.82833313, 0.20968327, 0.33328278],
        [0.04059322, 0.82791842, 0.86945209, 0.74014243, 0.94639682]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [99]:
#25 = value > d_min and value < d_mean
#75 = value > d_mean amd value < d_max
#50 = value = d_mean
#0 = value = d_min
#100 = value = d_max

f[(d>d_min) & (d<d_mean)] = 25
f[(d>d_mean) & (d<d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max] = 100

print(f)

[[[ 25.  25.  25.  25. 100.]
  [ 25.  75.  75.  25.  75.]]

 [[  0.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [100]:
print(d)

[[[1.30359978 1.24545779 1.41491716 1.40584203 1.95602968]
  [1.08448142 1.62466835 1.81075975 1.02188641 1.55388527]]

 [[1.02066276 1.66616803 1.24716398 1.63266224 1.86779775]
  [1.69970805 1.392821   1.92968533 1.23390818 1.03111999]]

 [[1.93142177 1.81427188 1.82833313 1.20968327 1.33328278]
  [1.04059322 1.82791842 1.86945209 1.74014243 1.94639682]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here