# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np


#### 2. Print your NumPy version.

In [4]:
np.__version__

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [36]:
# Method 1
a = np.random.randint(0, 100, size=(2, 3, 5))

a


array([[[82, 44, 48, 14, 62],
        [18, 87, 64,  9, 87],
        [88, 82, 53, 83, 62]],

       [[37,  9, 71, 16, 78],
        [18, 38, 95, 43, 74],
        [10,  1,  8, 83, 82]]])

In [9]:
# Method 2
np.random.rand(2, 3, 5)

array([[[0.9322445 , 0.17998943, 0.72903786, 0.70459918, 0.01627851],
        [0.59975562, 0.32577886, 0.60978882, 0.20535956, 0.62747512],
        [0.13028147, 0.46360926, 0.2089686 , 0.27976377, 0.6623368 ]],

       [[0.74851487, 0.7303775 , 0.12247742, 0.52988787, 0.58666679],
        [0.99790005, 0.71820396, 0.937603  , 0.09212625, 0.1077042 ],
        [0.97416482, 0.11378688, 0.72651857, 0.4378239 , 0.71641929]]])

In [16]:
# Method 3
np.array([np.random.randint(0, 100, 9), np.random.randint(0, 100, 9), np.random.randint(0, 100, 9)], ndmin=3) # ? 

array([[[94, 86,  9, 13, 88, 59, 46, 95, 56],
        [67, 16, 61, 28, 71, 86, 53, 43, 85],
        [ 6, 82, 94, 88, 33, 58, 28, 10, 71]]])

#### 4. Print *a*.


In [34]:
a

array([[[24,  4, 44, 92, 93],
        [66, 11, 97, 99, 69],
        [90, 38,  7,  5, 86]],

       [[62, 67, 67, 95, 20],
        [ 3, 84, 36, 15, 95],
        [11, 23, 16, 98, 37]]])

#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [31]:
b = np.ones((5, 3, 2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 6. Print *b*.


In [32]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [42]:
if a.size == b.size:
    print('This is how you prove it')

This is how you prove it


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
#You cannot add arrays with different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [45]:
c = b.transpose()


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
d = a + c
# A and C are the same size (we new it from before) but with the transpose they are also the same shape
d

array([[[83., 45., 49., 15., 63.],
        [19., 88., 65., 10., 88.],
        [89., 83., 54., 84., 63.]],

       [[38., 10., 72., 17., 79.],
        [19., 39., 96., 44., 75.],
        [11.,  2.,  9., 84., 83.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [53]:
print(a)
print(d)
print('Values in d are floats because when adding the array of 1s, they are also floats. Anyways, array a is the difference between array c and d')

[[[82 44 48 14 62]
  [18 87 64  9 87]
  [88 82 53 83 62]]

 [[37  9 71 16 78]
  [18 38 95 43 74]
  [10  1  8 83 82]]]
[[[83. 45. 49. 15. 63.]
  [19. 88. 65. 10. 88.]
  [89. 83. 54. 84. 63.]]

 [[38. 10. 72. 17. 79.]
  [19. 39. 96. 44. 75.]
  [11.  2.  9. 84. 83.]]]
Values in d are floats because when adding the array of 1s, they are also floats. Anyways, array a is the difference between array c and d


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [54]:
e = a * c
e

array([[[82., 44., 48., 14., 62.],
        [18., 87., 64.,  9., 87.],
        [88., 82., 53., 83., 62.]],

       [[37.,  9., 71., 16., 78.],
        [18., 38., 95., 43., 74.],
        [10.,  1.,  8., 83., 82.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
e == a
#They are equal because we just multiplied each value by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()


print(d_max)
print(d_min)
print(d_mean)

96.0
2.0
52.53333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [67]:
f = np.zeros((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [63]:
print(d_max)
print(d_min)
print(d_mean)


96.0
2.0
52.53333333333333


In [77]:
f[(d>d_min) & (d<d_mean)] = 25

f[(d>d_mean) & (d<d_max)] = 75

f[d == d_mean] = 50

f[d == d_min] = 0

f[d == d_max] = 100




#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
f
#yes... as required. 

array([[[ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[ 25.,  25.,  75.,  25.,  75.],
        [ 25.,  25., 100.,  25.,  75.],
        [ 25.,   0.,  25.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [76]:
f[(d>d_min) & (d<d_mean)] == 'B'
f[(d>d_mean) & (d<d_max)] == 'D'
f[d == d_mean] == 'C'
f[d == d_min] == 'A'
f[d == d_max] == 'E'
print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  25. 100.  25.  75.]
  [ 25.   0.  25.  75.  75.]]]


<ipython-input-76-a03a35ad6d43>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  f[(d>d_min) & (d<d_mean)] == 'B'
<ipython-input-76-a03a35ad6d43>:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  f[(d>d_mean) & (d<d_max)] == 'D'
<ipython-input-76-a03a35ad6d43>:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  f[d == d_mean] == 'C'
<ipython-input-76-a03a35ad6d43>:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  f[d == d_min] == 'A'
<ipython-input-76-a03a35ad6d43>:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  f[d == d_max] == 'E'
