# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
a = np.random.random((2,3,5))
print(a)

[[[0.96963577 0.4358349  0.53025673 0.38247853 0.67766617]
  [0.57653624 0.81124514 0.41973703 0.24414611 0.00716979]
  [0.2639845  0.05207476 0.20538134 0.37474608 0.2025286 ]]

 [[0.23464147 0.54589438 0.86796752 0.07476375 0.85261472]
  [0.07759832 0.00177002 0.2156768  0.94960217 0.72321143]
  [0.84510031 0.21283079 0.02404011 0.35984113 0.73970172]]]


In [4]:
a1=np.random.rand(2,3,5)
print(a1)

[[[0.75903488 0.13295792 0.35478913 0.95035648 0.80418176]
  [0.57184713 0.4288031  0.38996427 0.12207773 0.4122004 ]
  [0.34066878 0.7199042  0.10735431 0.38511236 0.44075347]]

 [[0.03235479 0.36856618 0.12587087 0.77324581 0.23635655]
  [0.43926145 0.9579086  0.47092487 0.97389032 0.07474572]
  [0.10489193 0.92161082 0.1090678  0.80114745 0.17637348]]]


In [5]:
a2=np.random.random_sample((2,3,5))
print(a2)

[[[0.14226609 0.66491069 0.1907927  0.98040176 0.17792889]
  [0.63597648 0.16660979 0.70765809 0.44024093 0.79530451]
  [0.13288236 0.56518562 0.61758293 0.58227707 0.33655857]]

 [[0.5856786  0.51626682 0.91358509 0.8555967  0.27518014]
  [0.73988765 0.39395702 0.85090865 0.57234258 0.97949224]
  [0.93517914 0.9605806  0.7621702  0.65551457 0.53732864]]]


#### 4. Print *a*.


In [6]:
print(a)

[[[0.96963577 0.4358349  0.53025673 0.38247853 0.67766617]
  [0.57653624 0.81124514 0.41973703 0.24414611 0.00716979]
  [0.2639845  0.05207476 0.20538134 0.37474608 0.2025286 ]]

 [[0.23464147 0.54589438 0.86796752 0.07476375 0.85261472]
  [0.07759832 0.00177002 0.2156768  0.94960217 0.72321143]
  [0.84510031 0.21283079 0.02404011 0.35984113 0.73970172]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
 b=np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
a+b #operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [33]:
c=np.reshape(b, (2, 3, 5))

In [37]:
b.shape

(5, 2, 3)

In [30]:
c=np.transpose(b)

In [36]:
(a).shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
d=a+c #because we reshape NOT transpose!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

the difference is **c** which is **b** aka ones , the relation is the shapes and **d** values are **a** values +1

In [35]:
a

array([[[0.96963577, 0.4358349 , 0.53025673, 0.38247853, 0.67766617],
        [0.57653624, 0.81124514, 0.41973703, 0.24414611, 0.00716979],
        [0.2639845 , 0.05207476, 0.20538134, 0.37474608, 0.2025286 ]],

       [[0.23464147, 0.54589438, 0.86796752, 0.07476375, 0.85261472],
        [0.07759832, 0.00177002, 0.2156768 , 0.94960217, 0.72321143],
        [0.84510031, 0.21283079, 0.02404011, 0.35984113, 0.73970172]]])

In [41]:
d

array([[[1.96963577, 1.4358349 , 1.53025673, 1.38247853, 1.67766617],
        [1.57653624, 1.81124514, 1.41973703, 1.24414611, 1.00716979],
        [1.2639845 , 1.05207476, 1.20538134, 1.37474608, 1.2025286 ]],

       [[1.23464147, 1.54589438, 1.86796752, 1.07476375, 1.85261472],
        [1.07759832, 1.00177002, 1.2156768 , 1.94960217, 1.72321143],
        [1.84510031, 1.21283079, 1.02404011, 1.35984113, 1.73970172]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [44]:
e==a  #c values are 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [49]:
d_max=np.max(d)

In [52]:
d_min=np.min(d)

In [53]:
d_mean=np.mean(d)

In [50]:
print(d_max)

1.9696357732387053


In [54]:
print(d_min)

1.0017700159286462


In [55]:
print(d_mean)

1.4292892102801782


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [84]:
f=np.empty([2,3,5])   # or f=np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [83]:
f=[i for i in d if i > d_min < d_mean f[]==25]

SyntaxError: invalid syntax (<ipython-input-83-304e2e1e69ff>, line 1)

In [87]:
f [ d == d_max ] = 100
f [ (d < d_max) & (d>d_mean)] = 75
f [ d == d_mean] = 50
f [ (d < d_mean) & (d>d_min)] = 25
f [ d == d_min ] = 0

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [88]:
print(f)

[[[100.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]]]


In [89]:
print(d)

[[[1.96963577 1.4358349  1.53025673 1.38247853 1.67766617]
  [1.57653624 1.81124514 1.41973703 1.24414611 1.00716979]
  [1.2639845  1.05207476 1.20538134 1.37474608 1.2025286 ]]

 [[1.23464147 1.54589438 1.86796752 1.07476375 1.85261472]
  [1.07759832 1.00177002 1.2156768  1.94960217 1.72321143]
  [1.84510031 1.21283079 1.02404011 1.35984113 1.73970172]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
f = f.astype(str)
f [ d == d_max ] = "A"
f [ (d < d_max) & (d>d_mean)] = "B"
f [ d == d_mean] = "C"
f [ (d < d_mean) & (d>d_min)] = "D"
f [ d == d_min ] = "E"
print(f)

[[['A' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']]

 [['D' 'B' 'B' 'D' 'B']
  ['D' 'E' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']]]
