# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [35]:
import numpy as np

#### 2. Print your NumPy version.

In [36]:
np.__version__

'1.20.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [37]:
# Method 1
a = np.random.random([2,3,5])
print(a)

[[[0.6081493  0.86208354 0.56403985 0.46397238 0.59544289]
  [0.10562904 0.43571496 0.49952062 0.08135973 0.86229178]
  [0.41313803 0.36495646 0.4389265  0.23239239 0.15797615]]

 [[0.66598743 0.34174784 0.09598615 0.67350649 0.22584448]
  [0.32185752 0.35010225 0.287649   0.28626435 0.94682377]
  [0.9731305  0.05695191 0.86646163 0.63712946 0.08069401]]]


In [38]:
# Method 2
rand_2 = np.random.ranf([2,3,5])
print(rand_2)

[[[0.15725321 0.91160217 0.57941136 0.80859257 0.9883052 ]
  [0.56955991 0.73777864 0.87693129 0.01102938 0.55188832]
  [0.32888506 0.14233514 0.89081943 0.30351449 0.38326318]]

 [[0.27143669 0.35633674 0.82004672 0.85486611 0.31893794]
  [0.11946949 0.0831813  0.81476809 0.08369259 0.9817324 ]
  [0.87228852 0.9954462  0.62479106 0.7353069  0.66600283]]]


#### 4. Print *a*.


In [39]:
# Method 3

rand_3 = np.random.random_sample([2,3,5])
print(rand_3)

[[[0.32830352 0.83318723 0.17282632 0.4099894  0.80775335]
  [0.21447646 0.73987181 0.04958143 0.08156052 0.91846585]
  [0.025048   0.44221116 0.81719001 0.00448163 0.61274584]]

 [[0.27889017 0.85468585 0.53913722 0.67275851 0.94260954]
  [0.59547465 0.35255643 0.28995114 0.4436712  0.64231787]
  [0.51715839 0.95742237 0.43833362 0.14742668 0.91865497]]]


In [40]:
# your code here
print(a)

[[[0.6081493  0.86208354 0.56403985 0.46397238 0.59544289]
  [0.10562904 0.43571496 0.49952062 0.08135973 0.86229178]
  [0.41313803 0.36495646 0.4389265  0.23239239 0.15797615]]

 [[0.66598743 0.34174784 0.09598615 0.67350649 0.22584448]
  [0.32185752 0.35010225 0.287649   0.28626435 0.94682377]
  [0.9731305  0.05695191 0.86646163 0.63712946 0.08069401]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [41]:
b = np.ones([5,2,3])

#### 6. Print *b*.


In [42]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [43]:
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [44]:
#c = a + b  ---> Returns: ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

# Even though they have the same size, they don't have the same shape so the computer doesn't know how to match
# elements from one with elements from the other

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [45]:
c = np.transpose(b,[1,2,0])

print(c)
np.shape(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
d = a+c

print(d)

[[[1.6081493  1.86208354 1.56403985 1.46397238 1.59544289]
  [1.10562904 1.43571496 1.49952062 1.08135973 1.86229178]
  [1.41313803 1.36495646 1.4389265  1.23239239 1.15797615]]

 [[1.66598743 1.34174784 1.09598615 1.67350649 1.22584448]
  [1.32185752 1.35010225 1.287649   1.28626435 1.94682377]
  [1.9731305  1.05695191 1.86646163 1.63712946 1.08069401]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
print(a)
print(d)

# Each value has been incremented by 1. This makes sense as d=a+c and c has 1 in every position.

[[[0.6081493  0.86208354 0.56403985 0.46397238 0.59544289]
  [0.10562904 0.43571496 0.49952062 0.08135973 0.86229178]
  [0.41313803 0.36495646 0.4389265  0.23239239 0.15797615]]

 [[0.66598743 0.34174784 0.09598615 0.67350649 0.22584448]
  [0.32185752 0.35010225 0.287649   0.28626435 0.94682377]
  [0.9731305  0.05695191 0.86646163 0.63712946 0.08069401]]]
[[[1.6081493  1.86208354 1.56403985 1.46397238 1.59544289]
  [1.10562904 1.43571496 1.49952062 1.08135973 1.86229178]
  [1.41313803 1.36495646 1.4389265  1.23239239 1.15797615]]

 [[1.66598743 1.34174784 1.09598615 1.67350649 1.22584448]
  [1.32185752 1.35010225 1.287649   1.28626435 1.94682377]
  [1.9731305  1.05695191 1.86646163 1.63712946 1.08069401]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
e = a*c
print(e)

[[[0.6081493  0.86208354 0.56403985 0.46397238 0.59544289]
  [0.10562904 0.43571496 0.49952062 0.08135973 0.86229178]
  [0.41313803 0.36495646 0.4389265  0.23239239 0.15797615]]

 [[0.66598743 0.34174784 0.09598615 0.67350649 0.22584448]
  [0.32185752 0.35010225 0.287649   0.28626435 0.94682377]
  [0.9731305  0.05695191 0.86646163 0.63712946 0.08069401]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
e == a

#Yes, because when multiplying two arrays of the same shape, each value in the array will be multiplied
# by the value that has the exact same position in the other array. As every element in c is 1, multiplying
# a*c leaves a as it was

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [70]:
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

1.9731305020282135
1.0569519132349594
1.449857681602641


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
f[((d<d_mean)& (d>d_min))] = 25
f[((d>d_mean)&(d<d_max))] = 75
f[(d==d_min)] = 0
f[(d==d_mean)] = 50
f[(d==d_max)] = 100
print(f)


[[[ 75.  75.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [100.   0.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [81]:
print(d)
print(f)

[[[1.6081493  1.86208354 1.56403985 1.46397238 1.59544289]
  [1.10562904 1.43571496 1.49952062 1.08135973 1.86229178]
  [1.41313803 1.36495646 1.4389265  1.23239239 1.15797615]]

 [[1.66598743 1.34174784 1.09598615 1.67350649 1.22584448]
  [1.32185752 1.35010225 1.287649   1.28626435 1.94682377]
  [1.9731305  1.05695191 1.86646163 1.63712946 1.08069401]]]
[[[ 75.  75.  75.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [100.   0.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [80]:
h = np.empty([2,3,5],dtype=str)

h[(d<d_mean)&(d>d_min)] = 'B'
h[(d>d_mean)&(d<d_max)] = 'D'
h[(d==d_min)] = 'A'
h[(d==d_mean)] = 'C'
h[(d==d_max)] = 'E'
print(h)

[[['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'B' 'B']]

 [['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['E' 'A' 'D' 'D' 'B']]]
