# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [4]:
np.random.seed(20)

In [5]:
np.random.choice([20, 30, 40, 50], size=(2,3,5))


array([[[50, 40, 50, 50, 20],
        [40, 30, 20, 50, 40],
        [50, 40, 20, 40, 20]],

       [[30, 40, 40, 50, 50],
        [20, 30, 40, 40, 40],
        [20, 30, 30, 50, 30]]])

In [6]:
z = np.random.randint(10, size=(2, 3, 5))

In [7]:
a = np.random.random((2,3,5)) #numpy.random.random(low/set, high/rows per set, shape/columns)
a

array([[[0.59813382, 0.82582358, 0.15639172, 0.73430052, 0.40864343],
        [0.7786879 , 0.80397057, 0.78607144, 0.59228702, 0.6644892 ],
        [0.64656729, 0.42563648, 0.51356833, 0.50125784, 0.03708381]],

       [[0.7081161 , 0.6204306 , 0.77780853, 0.45940947, 0.37980555],
        [0.2918922 , 0.55722886, 0.0841636 , 0.63128167, 0.94457049],
        [0.89123753, 0.87858258, 0.34475163, 0.70310053, 0.5273376 ]]])

# 4. Print *a*.


In [8]:
print(a)

[[[0.59813382 0.82582358 0.15639172 0.73430052 0.40864343]
  [0.7786879  0.80397057 0.78607144 0.59228702 0.6644892 ]
  [0.64656729 0.42563648 0.51356833 0.50125784 0.03708381]]

 [[0.7081161  0.6204306  0.77780853 0.45940947 0.37980555]
  [0.2918922  0.55722886 0.0841636  0.63128167 0.94457049]
  [0.89123753 0.87858258 0.34475163 0.70310053 0.5273376 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [9]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
b.size == a.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
np.add(a,b) # they cannot be added as the shapes are different a = 2,3,5 and b = 5,2,3

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [13]:
# your code here > try to do a reshape apply it to one of the arrays and then do transpose
# transpose  (= switch set/column?)

In [14]:
z # just for me to check where the numbers go with transpose

array([[[2, 6, 9, 3, 3],
        [9, 0, 6, 2, 3],
        [1, 8, 0, 2, 7]],

       [[6, 6, 8, 2, 1],
        [3, 2, 6, 9, 4],
        [6, 4, 8, 6, 2]]])

In [15]:
np.transpose(z)

array([[[2, 6],
        [9, 3],
        [1, 6]],

       [[6, 6],
        [0, 2],
        [8, 4]],

       [[9, 8],
        [6, 6],
        [0, 8]],

       [[3, 2],
        [2, 9],
        [2, 6]],

       [[3, 1],
        [3, 4],
        [7, 2]]])

In [16]:
b = np.reshape(b, (5,3,2)) #set 5 row 3 column 2
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
c = np.transpose(b) #set 2 row 3 column 5
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [18]:
d = np.add(a,c) # it works because it has the exact same shape
d

array([[[1.59813382, 1.82582358, 1.15639172, 1.73430052, 1.40864343],
        [1.7786879 , 1.80397057, 1.78607144, 1.59228702, 1.6644892 ],
        [1.64656729, 1.42563648, 1.51356833, 1.50125784, 1.03708381]],

       [[1.7081161 , 1.6204306 , 1.77780853, 1.45940947, 1.37980555],
        [1.2918922 , 1.55722886, 1.0841636 , 1.63128167, 1.94457049],
        [1.89123753, 1.87858258, 1.34475163, 1.70310053, 1.5273376 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [19]:
print(a)
print('\n')
print(d)  
# they are exactly the same but +1 (array b)

[[[0.59813382 0.82582358 0.15639172 0.73430052 0.40864343]
  [0.7786879  0.80397057 0.78607144 0.59228702 0.6644892 ]
  [0.64656729 0.42563648 0.51356833 0.50125784 0.03708381]]

 [[0.7081161  0.6204306  0.77780853 0.45940947 0.37980555]
  [0.2918922  0.55722886 0.0841636  0.63128167 0.94457049]
  [0.89123753 0.87858258 0.34475163 0.70310053 0.5273376 ]]]


[[[1.59813382 1.82582358 1.15639172 1.73430052 1.40864343]
  [1.7786879  1.80397057 1.78607144 1.59228702 1.6644892 ]
  [1.64656729 1.42563648 1.51356833 1.50125784 1.03708381]]

 [[1.7081161  1.6204306  1.77780853 1.45940947 1.37980555]
  [1.2918922  1.55722886 1.0841636  1.63128167 1.94457049]
  [1.89123753 1.87858258 1.34475163 1.70310053 1.5273376 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [20]:
e = np.multiply(a,c)
e

array([[[0.59813382, 0.82582358, 0.15639172, 0.73430052, 0.40864343],
        [0.7786879 , 0.80397057, 0.78607144, 0.59228702, 0.6644892 ],
        [0.64656729, 0.42563648, 0.51356833, 0.50125784, 0.03708381]],

       [[0.7081161 , 0.6204306 , 0.77780853, 0.45940947, 0.37980555],
        [0.2918922 , 0.55722886, 0.0841636 , 0.63128167, 0.94457049],
        [0.89123753, 0.87858258, 0.34475163, 0.70310053, 0.5273376 ]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
e == a 
# because all elements were multiplied by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [22]:
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.944570487920368
1.0370838109187992
1.5757543303899522


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [23]:
f = np.zeros((2,3,5))   # how would that go with np.empty?
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
print(d)

[[[1.59813382 1.82582358 1.15639172 1.73430052 1.40864343]
  [1.7786879  1.80397057 1.78607144 1.59228702 1.6644892 ]
  [1.64656729 1.42563648 1.51356833 1.50125784 1.03708381]]

 [[1.7081161  1.6204306  1.77780853 1.45940947 1.37980555]
  [1.2918922  1.55722886 1.0841636  1.63128167 1.94457049]
  [1.89123753 1.87858258 1.34475163 1.70310053 1.5273376 ]]]


In [25]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max] = 100
f

array([[[ 75.,  75.,  25.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,   0.]],

       [[ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  75., 100.],
        [ 75.,  75.,  25.,  75.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
print(d)
print('\n')
print(f) 
# answer: yes

[[[1.59813382 1.82582358 1.15639172 1.73430052 1.40864343]
  [1.7786879  1.80397057 1.78607144 1.59228702 1.6644892 ]
  [1.64656729 1.42563648 1.51356833 1.50125784 1.03708381]]

 [[1.7081161  1.6204306  1.77780853 1.45940947 1.37980555]
  [1.2918922  1.55722886 1.0841636  1.63128167 1.94457049]
  [1.89123753 1.87858258 1.34475163 1.70310053 1.5273376 ]]]


[[[ 75.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.   0.]]

 [[ 75.  75.  75.  25.  25.]
  [ 25.  25.  25.  75. 100.]
  [ 75.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
f = f.astype(str)

f[(d > d_min) & (d < d_mean)] = 'B'
f[(d > d_mean) & (d < d_max)] = 'D'
f[d==d_mean] = 'C'
f[d==d_min] = 'A'
f[d==d_max] = 'E'

print(f)

[[['D' 'D' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'A']]

 [['D' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'D' 'E']
  ['D' 'D' 'B' 'D' 'B']]]
