# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [5]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.39081758, 0.91592776, 0.64177224, 0.23649816, 0.93410343],
        [0.94922711, 0.24172548, 0.79578745, 0.09831732, 0.71567027],
        [0.95066194, 0.15647249, 0.34594066, 0.59782275, 0.89309087]],

       [[0.1588084 , 0.50704356, 0.63601393, 0.93271946, 0.15710614],
        [0.30654266, 0.10424907, 0.12346093, 0.1915759 , 0.22836841],
        [0.36603261, 0.91489244, 0.86624534, 0.10308593, 0.51178912]]])

In [6]:
# Method 2
l = np.random.normal(0,1, (2,3,5))
l

array([[[ 1.56248112, -1.15310198, -0.38170722, -1.29357329,
         -1.15994242],
        [ 0.31460586,  0.20098848,  0.65481243,  1.50250966,
         -1.6581195 ],
        [-1.05752271, -1.17021461, -1.34233658, -1.51392149,
         -0.42795214]],

       [[ 0.01169744,  0.58931666,  0.40482963, -1.61365745,
         -0.09674433],
        [ 0.87179559, -0.81794802,  0.35375027, -0.79369803,
          0.22222818],
        [ 1.38457114,  0.45259949,  0.23183974, -0.89921648,
         -0.92855059]]])

In [7]:
# Method 3
j = np.random.randint(0,150, (2,3,5))
j

array([[[ 59, 116,  48,  74,  39],
        [141,  33,  51,  20,  20],
        [ 46,  54,  63,   9, 134]],

       [[ 87,  73,  27,  95,  10],
        [  7,   1,  22, 122,  51],
        [ 63,  18,  46,  57, 128]]])

#### 4. Print *a*.


In [8]:
# your code here
print(a)

[[[0.39081758 0.91592776 0.64177224 0.23649816 0.93410343]
  [0.94922711 0.24172548 0.79578745 0.09831732 0.71567027]
  [0.95066194 0.15647249 0.34594066 0.59782275 0.89309087]]

 [[0.1588084  0.50704356 0.63601393 0.93271946 0.15710614]
  [0.30654266 0.10424907 0.12346093 0.1915759  0.22836841]
  [0.36603261 0.91489244 0.86624534 0.10308593 0.51178912]]]


#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [9]:
# your code here
b = np.random.normal(1,0, (5,3,2))

#### 6. Print *b*.


In [10]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here
# You cant add them because they dont have the same shape!
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [13]:
# your code here
c = np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
# It works because they both have the same shape now!
d = a + c
print(d)

[[[1.39081758 1.91592776 1.64177224 1.23649816 1.93410343]
  [1.94922711 1.24172548 1.79578745 1.09831732 1.71567027]
  [1.95066194 1.15647249 1.34594066 1.59782275 1.89309087]]

 [[1.1588084  1.50704356 1.63601393 1.93271946 1.15710614]
  [1.30654266 1.10424907 1.12346093 1.1915759  1.22836841]
  [1.36603261 1.91489244 1.86624534 1.10308593 1.51178912]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
# we added the 1 from each index of array c to the values of a, so they just increased by 1.
print(a)
print("\n")
print(d)

[[[0.39081758 0.91592776 0.64177224 0.23649816 0.93410343]
  [0.94922711 0.24172548 0.79578745 0.09831732 0.71567027]
  [0.95066194 0.15647249 0.34594066 0.59782275 0.89309087]]

 [[0.1588084  0.50704356 0.63601393 0.93271946 0.15710614]
  [0.30654266 0.10424907 0.12346093 0.1915759  0.22836841]
  [0.36603261 0.91489244 0.86624534 0.10308593 0.51178912]]]


[[[1.39081758 1.91592776 1.64177224 1.23649816 1.93410343]
  [1.94922711 1.24172548 1.79578745 1.09831732 1.71567027]
  [1.95066194 1.15647249 1.34594066 1.59782275 1.89309087]]

 [[1.1588084  1.50704356 1.63601393 1.93271946 1.15710614]
  [1.30654266 1.10424907 1.12346093 1.1915759  1.22836841]
  [1.36603261 1.91489244 1.86624534 1.10308593 1.51178912]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e = a*c
print(e)

[[[0.39081758 0.91592776 0.64177224 0.23649816 0.93410343]
  [0.94922711 0.24172548 0.79578745 0.09831732 0.71567027]
  [0.95066194 0.15647249 0.34594066 0.59782275 0.89309087]]

 [[0.1588084  0.50704356 0.63601393 0.93271946 0.15710614]
  [0.30654266 0.10424907 0.12346093 0.1915759  0.22836841]
  [0.36603261 0.91489244 0.86624534 0.10308593 0.51178912]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
# Yes its the same, because you just multiply it by one according to c.
a == e 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9506619445716324
1.0983173204754975
1.499058981076453


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [19]:
# your code here
f = np.zeros((2,3,5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
f[(d>d_min)&(d<d_mean)]=25
f[(d<d_max) & (d>d_mean)]=75
f[d==d_mean]=50
f[d==d_max]=100
f[d==d_min]=0

print(f)

[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.   0.  75.]
  [100.  25.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print(f)
print("\n")
print(d)

[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.   0.  75.]
  [100.  25.  25.  75.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.  75.  25.  75.]]]


[[[1.39081758 1.91592776 1.64177224 1.23649816 1.93410343]
  [1.94922711 1.24172548 1.79578745 1.09831732 1.71567027]
  [1.95066194 1.15647249 1.34594066 1.59782275 1.89309087]]

 [[1.1588084  1.50704356 1.63601393 1.93271946 1.15710614]
  [1.30654266 1.10424907 1.12346093 1.1915759  1.22836841]
  [1.36603261 1.91489244 1.86624534 1.10308593 1.51178912]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here