# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [18]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.88241956, 0.1239464 , 0.35494488, 0.14623245, 0.63105579],
        [0.64470747, 0.27901257, 0.94997033, 0.98159757, 0.81759509],
        [0.43691888, 0.61981146, 0.2798251 , 0.55087866, 0.85391699]],

       [[0.72105098, 0.52340931, 0.71476921, 0.87653887, 0.69464453],
        [0.35642933, 0.79571055, 0.52411689, 0.17197375, 0.4967694 ],
        [0.81276052, 0.72695187, 0.53374369, 0.73009443, 0.38024943]]])

In [19]:
# Method 2
np.random.normal(0,1,(2,3,5))

array([[[ 0.90752054,  0.57810183, -1.46142042,  1.12565711,
          0.54186794],
        [-0.25102412, -0.27612718,  0.3775659 , -0.51562637,
         -1.01755662],
        [ 0.80223558, -0.77309418,  0.70268225,  1.13420486,
         -1.50468013]],

       [[-0.43317359, -0.01781617,  0.09135775, -0.46228936,
         -0.79960893],
        [-0.06399447,  0.07467563, -0.5272238 , -0.54356004,
          0.26459604],
        [ 0.66070848, -0.19166466, -0.43853147, -1.09938988,
          2.15282496]]])

In [26]:
# Method 3
np.random.uniform(0, 10, (2, 3, 5))

array([[[9.56121308, 3.58386264, 7.62575259, 1.94925004, 5.37899471],
        [4.44305296, 0.49111378, 1.7075075 , 5.6931339 , 3.58384596],
        [9.57873417, 4.4068657 , 3.06477877, 4.3132436 , 7.30506149]],

       [[3.15974493, 9.33412271, 2.98073298, 5.06879093, 7.46326327],
        [5.41628397, 2.31949111, 1.53744945, 6.43258901, 8.70441436],
        [5.06565387, 3.85221554, 6.47017167, 8.74282981, 4.78710877]]])

In [ ]:
# np.random.randint(0, 10, (2, 3, 5))

#### 4. Print *a*.


In [21]:
# your code here
print(a)

[[[0.88241956 0.1239464  0.35494488 0.14623245 0.63105579]
  [0.64470747 0.27901257 0.94997033 0.98159757 0.81759509]
  [0.43691888 0.61981146 0.2798251  0.55087866 0.85391699]]

 [[0.72105098 0.52340931 0.71476921 0.87653887 0.69464453]
  [0.35642933 0.79571055 0.52411689 0.17197375 0.4967694 ]
  [0.81276052 0.72695187 0.53374369 0.73009443 0.38024943]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [22]:
# your code here
b = np.ones((5,2,3))   # Create an array of all ones

#### 6. Print *b*.


In [23]:
# your code here
print(b, "\n")

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 



In [38]:
b.shape

(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [80]:
# your answer here
# np.add(a,b)   - operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [82]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [84]:
# your code/answer here
d = np.add (a,c)  # d = a + c
d                 # because they have the same shape

array([[[1.88241956, 1.1239464 , 1.35494488, 1.14623245, 1.63105579],
        [1.64470747, 1.27901257, 1.94997033, 1.98159757, 1.81759509],
        [1.43691888, 1.61981146, 1.2798251 , 1.55087866, 1.85391699]],

       [[1.72105098, 1.52340931, 1.71476921, 1.87653887, 1.69464453],
        [1.35642933, 1.79571055, 1.52411689, 1.17197375, 1.4967694 ],
        [1.81276052, 1.72695187, 1.53374369, 1.73009443, 1.38024943]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [103]:
# your code/answer here
print("a: ", a)   # concatenation happened
print( )
print("d: ", d)   # since every element in c is one, that the difference to a elements 

a:  [[[0.88241956 0.1239464  0.35494488 0.14623245 0.63105579]
  [0.64470747 0.27901257 0.94997033 0.98159757 0.81759509]
  [0.43691888 0.61981146 0.2798251  0.55087866 0.85391699]]

 [[0.72105098 0.52340931 0.71476921 0.87653887 0.69464453]
  [0.35642933 0.79571055 0.52411689 0.17197375 0.4967694 ]
  [0.81276052 0.72695187 0.53374369 0.73009443 0.38024943]]]

d:  [[[1.88241956 1.1239464  1.35494488 1.14623245 1.63105579]
  [1.64470747 1.27901257 1.94997033 1.98159757 1.81759509]
  [1.43691888 1.61981146 1.2798251  1.55087866 1.85391699]]

 [[1.72105098 1.52340931 1.71476921 1.87653887 1.69464453]
  [1.35642933 1.79571055 1.52411689 1.17197375 1.4967694 ]
  [1.81276052 1.72695187 1.53374369 1.73009443 1.38024943]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [104]:
# your code here
e = a * c
e

array([[[0.88241956, 0.1239464 , 0.35494488, 0.14623245, 0.63105579],
        [0.64470747, 0.27901257, 0.94997033, 0.98159757, 0.81759509],
        [0.43691888, 0.61981146, 0.2798251 , 0.55087866, 0.85391699]],

       [[0.72105098, 0.52340931, 0.71476921, 0.87653887, 0.69464453],
        [0.35642933, 0.79571055, 0.52411689, 0.17197375, 0.4967694 ],
        [0.81276052, 0.72695187, 0.53374369, 0.73009443, 0.38024943]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [105]:
# your code/answer here
e == a    

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [106]:
# your code here
d_mean = np.mean(d)
d_mean

1.5870681990629052

In [107]:
d_max = np.max(d)
d_max

1.981597571742987

In [108]:
d_min = np.min(d)
d_min

1.123946399336613

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [109]:
# your code here
f = np.zeros((2,3,5))   # f = np.empty_like(d)
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [121]:
print(d)

[[[1.88241956 1.1239464  1.35494488 1.14623245 1.63105579]
  [1.64470747 1.27901257 1.94997033 1.98159757 1.81759509]
  [1.43691888 1.61981146 1.2798251  1.55087866 1.85391699]]

 [[1.72105098 1.52340931 1.71476921 1.87653887 1.69464453]
  [1.35642933 1.79571055 1.52411689 1.17197375 1.4967694 ]
  [1.81276052 1.72695187 1.53374369 1.73009443 1.38024943]]]


In [122]:
# your code here
f [ d == d_max ] = 100
f [ (d < d_max) & (d > d_mean)] = 75
f [ d == d_mean] = 50
f [ (d < d_mean) & (d > d_min) ] = 25
f [ d == d_min ] = 0
print(f)

[[[ 75.   0.  25.  25.  75.]
  [ 75.  25.  75. 100.  75.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  75.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [124]:
# your code here
d

array([[[1.88241956, 1.1239464 , 1.35494488, 1.14623245, 1.63105579],
        [1.64470747, 1.27901257, 1.94997033, 1.98159757, 1.81759509],
        [1.43691888, 1.61981146, 1.2798251 , 1.55087866, 1.85391699]],

       [[1.72105098, 1.52340931, 1.71476921, 1.87653887, 1.69464453],
        [1.35642933, 1.79571055, 1.52411689, 1.17197375, 1.4967694 ],
        [1.81276052, 1.72695187, 1.53374369, 1.73009443, 1.38024943]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [125]:
# your code here

f = f.astype(str)

f [ d == d_max ] = "A"
f [ (d < d_max) & (d > d_mean)] = "B"
f [ d == d_mean] = "C"
f [ (d < d_mean) & (d > d_min) ] = "D"
f [ d == d_min ] = "E"
print(f)

[[['B' 'E' 'D' 'D' 'B']
  ['B' 'D' 'B' 'A' 'B']
  ['D' 'B' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']]]
