# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [15]:
import numpy as np

#### 2. Print your NumPy version.

In [16]:
np.__version__

'1.20.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [17]:
c = np.random.random_sample((2, 3, 5))
c

array([[[0.69139067, 0.24132612, 0.48130727, 0.83923079, 0.73783214],
        [0.61785393, 0.12046153, 0.20364627, 0.86876345, 0.1383595 ],
        [0.88162593, 0.54499234, 0.1458281 , 0.65260304, 0.26819971]],

       [[0.22825512, 0.36386216, 0.34978009, 0.83471157, 0.02058762],
        [0.34136818, 0.87288659, 0.02300904, 0.32342131, 0.97847924],
        [0.48959679, 0.58178683, 0.43407079, 0.34648231, 0.17948129]]])

In [18]:
np.random.rand(2, 3, 5)

array([[[0.8127403 , 0.90816162, 0.90628201, 0.94419181, 0.30008636],
        [0.6155429 , 0.55212312, 0.81970148, 0.54304933, 0.23338443],
        [0.94894401, 0.18409518, 0.95558629, 0.26971466, 0.3680478 ]],

       [[0.25963203, 0.6041489 , 0.31895609, 0.6109431 , 0.78830676],
        [0.83647915, 0.30551645, 0.71555576, 0.99158059, 0.44486229],
        [0.65152211, 0.44879173, 0.93158235, 0.23011168, 0.59480807]]])

In [19]:
a = np.random.random((2, 3, 5))

#### 4. Print *a*.


In [20]:
print(a)

[[[0.89480189 0.87009166 0.68784257 0.40642693 0.5271626 ]
  [0.21441693 0.38449637 0.14247224 0.55632427 0.22224078]
  [0.7585183  0.77332562 0.33609046 0.53198265 0.35894932]]

 [[0.4328246  0.65770301 0.23998851 0.55914871 0.70768504]
  [0.43163131 0.52888585 0.58863512 0.90581015 0.48825682]
  [0.80532898 0.51893363 0.16643115 0.02184814 0.70831851]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [21]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [22]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
a.shape

(2, 3, 5)

In [25]:
b.shape

(5, 2, 3)

In [26]:
a + b #The error message shows the two shapes of a and b, so without changing the shape you cannot add those two.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [27]:
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
a.shape

(2, 3, 5)

In [29]:
c.shape

(2, 3, 5)

In [49]:
d = a+c #They have the same shape.
d

array([[[1.89480189, 1.87009166, 1.68784257, 1.40642693, 1.5271626 ],
        [1.21441693, 1.38449637, 1.14247224, 1.55632427, 1.22224078],
        [1.7585183 , 1.77332562, 1.33609046, 1.53198265, 1.35894932]],

       [[1.4328246 , 1.65770301, 1.23998851, 1.55914871, 1.70768504],
        [1.43163131, 1.52888585, 1.58863512, 1.90581015, 1.48825682],
        [1.80532898, 1.51893363, 1.16643115, 1.02184814, 1.70831851]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [50]:
print(a)

[[[0.89480189 0.87009166 0.68784257 0.40642693 0.5271626 ]
  [0.21441693 0.38449637 0.14247224 0.55632427 0.22224078]
  [0.7585183  0.77332562 0.33609046 0.53198265 0.35894932]]

 [[0.4328246  0.65770301 0.23998851 0.55914871 0.70768504]
  [0.43163131 0.52888585 0.58863512 0.90581015 0.48825682]
  [0.80532898 0.51893363 0.16643115 0.02184814 0.70831851]]]


In [51]:
print(d)

[[[1.89480189 1.87009166 1.68784257 1.40642693 1.5271626 ]
  [1.21441693 1.38449637 1.14247224 1.55632427 1.22224078]
  [1.7585183  1.77332562 1.33609046 1.53198265 1.35894932]]

 [[1.4328246  1.65770301 1.23998851 1.55914871 1.70768504]
  [1.43163131 1.52888585 1.58863512 1.90581015 1.48825682]
  [1.80532898 1.51893363 1.16643115 1.02184814 1.70831851]]]


In [52]:
explain = d - a
explain # d is a + 1 for every number, when substract a you get an array with ones.

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
e = a*c
e

array([[[0.89480189, 0.87009166, 0.68784257, 0.40642693, 0.5271626 ],
        [0.21441693, 0.38449637, 0.14247224, 0.55632427, 0.22224078],
        [0.7585183 , 0.77332562, 0.33609046, 0.53198265, 0.35894932]],

       [[0.4328246 , 0.65770301, 0.23998851, 0.55914871, 0.70768504],
        [0.43163131, 0.52888585, 0.58863512, 0.90581015, 0.48825682],
        [0.80532898, 0.51893363, 0.16643115, 0.02184814, 0.70831851]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
e == a #c is an array full of ones, so multiplying c with a does not change the numbers.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
d_max = d.max()
d_max

1.9058101508283944

In [37]:
d_min = d.min()
d_min

1.021848138033822

In [38]:
d_mean = d.mean()
d_mean

1.5142190705669105

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
f = np.zeros([2,3,5])
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
f[d==d_max] = 100
f[d==d_mean] = 75
f[d==d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[(d < d_max) & (d > d_mean)] = 75
f

array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[ 25.,  75.,  25.,  75.,  75.],
        [ 25.,  75.,  75., 100.,  25.],
        [ 75.,  75.,  25.,   0.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here