# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [8]:
#a= np.random.normal(size=(2,3,5))  # First way

In [67]:
a = np.random.randint(low=1,  high=1000, size=(2,3,5))   # Second way

In [31]:
from numpy.random import uniform


#a = np.random.uniform(size=(2,3,5))  #Third way

#### 4. Print *a*.


In [68]:
a

array([[[776, 109, 816, 849, 306],
        [813, 814, 666, 214, 939],
        [587, 100, 158, 963,  70]],

       [[363, 898, 975, 462, 421],
        [625, 723, 847, 129, 730],
        [638, 972, 749,  49, 853]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [80]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [81]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [82]:
a.size == b.size  # They have the same size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [88]:
np.add(a,b)


#It's not possible because the have different shapes (all the array dimensions for the concatenation must muatch exactly)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [89]:
c = b.reshape(2,3,5)

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [85]:
a

array([[[776, 109, 816, 849, 306],
        [813, 814, 666, 214, 939],
        [587, 100, 158, 963,  70]],

       [[363, 898, 975, 462, 421],
        [625, 723, 847, 129, 730],
        [638, 972, 749,  49, 853]]])

In [90]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [91]:
d = np.add(a,c)

d

array([[[777., 110., 817., 850., 307.],
        [814., 815., 667., 215., 940.],
        [588., 101., 159., 964.,  71.]],

       [[364., 899., 976., 463., 422.],
        [626., 724., 848., 130., 731.],
        [639., 973., 750.,  50., 854.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# Basically, d is adding the values in the arrays a and c

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [92]:
e = a*c

e

array([[[776., 109., 816., 849., 306.],
        [813., 814., 666., 214., 939.],
        [587., 100., 158., 963.,  70.]],

       [[363., 898., 975., 462., 421.],
        [625., 723., 847., 129., 730.],
        [638., 972., 749.,  49., 853.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [93]:
# e is equal to a becaause is multiplying the values for 1. We can check this with Python:

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [98]:
d_max=d.max()
print("The maximum value in d is:",d.max())
d_min=d.min()
print("The minimum value in d is:",d.min())
d_mean=d.mean()
print("The average value in d is:",d.mean())

The maximum value in d is: 976.0
The minimum value in d is: 50.0
The average value in d is: 588.1333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [106]:
f = np.empty_like(d)

f


array([[[776., 109., 816., 849., 306.],
        [813., 814., 666., 214., 939.],
        [587., 100., 158., 963.,  70.]],

       [[363., 898., 975., 462., 421.],
        [625., 723., 847., 129., 730.],
        [638., 972., 749.,  49., 853.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: <span class="mark">you don't have to use Numpy in this question.</span>

In [113]:
f [ d == d_max ] = 100
f [ (d < d_max) & (d>d_mean)] = 75
f [ d == d_mean] = 50
f [ (d < d_mean) & (d>d_min)] = 25
f [ d == d_min ] = 0

print(f)

[[['75' '25' '75' '75' '25']
  ['75' '75' '75' '25' '75']
  ['25' '25' '25' '75' '25']]

 [['25' '75' '100' '25' '25']
  ['75' '75' '75' '25' '75']
  ['75' '75' '75' '0' '75']]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [111]:
print(d)

[[[777. 110. 817. 850. 307.]
  [814. 815. 667. 215. 940.]
  [588. 101. 159. 964.  71.]]

 [[364. 899. 976. 463. 422.]
  [626. 724. 848. 130. 731.]
  [639. 973. 750.  50. 854.]]]


In [114]:
print(f)

[[['75' '25' '75' '75' '25']
  ['75' '75' '75' '25' '75']
  ['25' '25' '25' '75' '25']]

 [['25' '75' '100' '25' '25']
  ['75' '75' '75' '25' '75']
  ['75' '75' '75' '0' '75']]]


Yes, I've got my expected f

#### 18. <span class="burk">Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:</span>

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [115]:
f = f.astype(str)

f [ d == d_max ] = "A"
f [ (d < d_max) & (d>d_mean)] = "B"
f [ d == d_mean] = "C"
f [ (d < d_mean) & (d>d_min)] = "D"
f [ d == d_min ] = "E"

print(f)

[[['B' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']]

 [['D' 'B' 'A' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'E' 'B']]]
