# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.__version__

'1.20.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [46]:
# Method 1
a = np.random.random([2,3,5])
a
#type(a)

array([[[0.03082189, 0.93915573, 0.25683772, 0.0571346 , 0.38770822],
        [0.35709675, 0.98638414, 0.93959064, 0.58277522, 0.99310313],
        [0.9899145 , 0.86505637, 0.16171823, 0.36849024, 0.30672666]],

       [[0.34086324, 0.29047775, 0.63786407, 0.050654  , 0.93518431],
        [0.02584484, 0.53163905, 0.07160379, 0.69149444, 0.11708751],
        [0.19351251, 0.9123815 , 0.31071241, 0.3156425 , 0.80703011]]])

In [47]:
# Method 2
np.ndarray(shape=(2,3,5)) # found from reference https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray



array([[[0.03082189, 0.93915573, 0.25683772, 0.0571346 , 0.38770822],
        [0.35709675, 0.98638414, 0.93959064, 0.58277522, 0.99310313],
        [0.9899145 , 0.86505637, 0.16171823, 0.36849024, 0.30672666]],

       [[0.34086324, 0.29047775, 0.63786407, 0.050654  , 0.93518431],
        [0.02584484, 0.53163905, 0.07160379, 0.69149444, 0.11708751],
        [0.19351251, 0.9123815 , 0.31071241, 0.3156425 , 0.80703011]]])

In [72]:
# Method 3
np.random.randn(2,3,5)
print(np.random.randn(2,3,5))

[[[-0.3887465  -0.10437829  0.22850879  1.93340251 -0.9245254 ]
  [ 0.36668562  0.59495425  2.07441262 -0.06431477  0.50304305]
  [-0.6389601   0.39805584 -0.49668004 -0.19036585 -0.78607455]]

 [[-0.24324387  2.18328304 -1.40853733 -0.40392631  1.02999534]
  [-0.84491883 -1.47639136  0.05884045  1.99322526  0.43523388]
  [ 0.58558141 -0.66651731  0.00542622 -1.7206549   1.67023797]]]


In [92]:
np.random.normal(size=[2,3,5]) # here i just tried one more method! Instead of shape, size also give us the same array!

#or we can also use the following:
np.random.randint(low=1, high=1000, size=(2,3,5)) #with assiging lowest and highest int to be generated !




array([[[986, 535, 685, 344, 143],
        [689, 783, 257, 449, 387],
        [136, 178, 307, 183, 347]],

       [[669, 741,  78, 436, 557],
        [217, 547, 226, 537, 947],
        [260, 996, 701, 240, 206]]])

#### 4. Print *a*.


In [84]:
# your code here
print(a)

[[[0.03082189 0.93915573 0.25683772 0.0571346  0.38770822]
  [0.35709675 0.98638414 0.93959064 0.58277522 0.99310313]
  [0.9899145  0.86505637 0.16171823 0.36849024 0.30672666]]

 [[0.34086324 0.29047775 0.63786407 0.050654   0.93518431]
  [0.02584484 0.53163905 0.07160379 0.69149444 0.11708751]
  [0.19351251 0.9123815  0.31071241 0.3156425  0.80703011]]]


#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [67]:
# your code here
b = np.ones([5,3,2])

#### 6. Print *b*.


In [85]:
# your code here
print(b)
type(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


numpy.ndarray

In [69]:
np.random.normal(size=[2,3,5])

array([[[-1.10014381, -1.31564409,  0.81050091, -1.04477837,
         -0.68922937],
        [-0.85275686,  1.11347211, -1.92116972, -0.70140242,
          0.84908785],
        [ 1.05069979, -0.53687446, -0.02919272,  1.39405598,
         -0.39786744]],

       [[ 1.01912738,  1.8988813 , -0.35484964, -0.38701647,
         -1.92730539],
        [ 0.55075659,  0.95435581,  0.7827765 , -1.7932379 ,
          1.2418555 ],
        [ 1.70774688,  0.3231534 , -0.99183439, -1.16328237,
         -0.0213351 ]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [76]:
# your code here

if np.size(a) == np.size(b):
    print("Their size are same")
else:
    print("Their size are not same")


Their size are same


#### 8. Are you able to add *a* and *b*? Why or why not?


In [77]:
# your answer here
arr_add = np.add(a, b)
# It cannot add because they have different array pattern, [2,3,5] & [5,3,2].
#see below error for more explanation if you run this code.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [80]:
# your code here
c = b.T
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [86]:
# your code/answer here
d = np.add(a,c)
print(d)
# We can add both the arrays because they have same dimensional shape, i.e.2x3x5 3-dimensional 

[[[1.03082189 1.93915573 1.25683772 1.0571346  1.38770822]
  [1.35709675 1.98638414 1.93959064 1.58277522 1.99310313]
  [1.9899145  1.86505637 1.16171823 1.36849024 1.30672666]]

 [[1.34086324 1.29047775 1.63786407 1.050654   1.93518431]
  [1.02584484 1.53163905 1.07160379 1.69149444 1.11708751]
  [1.19351251 1.9123815  1.31071241 1.3156425  1.80703011]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [88]:
# your code/answer here
print(a)
print(d)

#Array a has randomly generated values in shape 2x3x5 and when we created another
# array d with transposing c (c was created with full ones), then shape of c became 2x3x5 same as a
#hence we were able to add them and values from both of them added together which can be seen clearly
#when we print a & d.

[[[0.03082189 0.93915573 0.25683772 0.0571346  0.38770822]
  [0.35709675 0.98638414 0.93959064 0.58277522 0.99310313]
  [0.9899145  0.86505637 0.16171823 0.36849024 0.30672666]]

 [[0.34086324 0.29047775 0.63786407 0.050654   0.93518431]
  [0.02584484 0.53163905 0.07160379 0.69149444 0.11708751]
  [0.19351251 0.9123815  0.31071241 0.3156425  0.80703011]]]
[[[1.03082189 1.93915573 1.25683772 1.0571346  1.38770822]
  [1.35709675 1.98638414 1.93959064 1.58277522 1.99310313]
  [1.9899145  1.86505637 1.16171823 1.36849024 1.30672666]]

 [[1.34086324 1.29047775 1.63786407 1.050654   1.93518431]
  [1.02584484 1.53163905 1.07160379 1.69149444 1.11708751]
  [1.19351251 1.9123815  1.31071241 1.3156425  1.80703011]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [90]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.03082189 0.93915573 0.25683772 0.0571346  0.38770822]
  [0.35709675 0.98638414 0.93959064 0.58277522 0.99310313]
  [0.9899145  0.86505637 0.16171823 0.36849024 0.30672666]]

 [[0.34086324 0.29047775 0.63786407 0.050654   0.93518431]
  [0.02584484 0.53163905 0.07160379 0.69149444 0.11708751]
  [0.19351251 0.9123815  0.31071241 0.3156425  0.80703011]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [93]:
# your code/answer here
print(a)
# True, a is equal to e. Because c is full of ones and hence when we multiply whatever number with 1, it gives 
# us the same value!

[[[0.03082189 0.93915573 0.25683772 0.0571346  0.38770822]
  [0.35709675 0.98638414 0.93959064 0.58277522 0.99310313]
  [0.9899145  0.86505637 0.16171823 0.36849024 0.30672666]]

 [[0.34086324 0.29047775 0.63786407 0.050654   0.93518431]
  [0.02584484 0.53163905 0.07160379 0.69149444 0.11708751]
  [0.19351251 0.9123815  0.31071241 0.3156425  0.80703011]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [107]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [111]:
d_max

1.9931031337764242

In [112]:
d_min

1.025844836873523

In [113]:
d_mean

1.481816869843416

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [149]:
# your code here
f = np.zeros([2,3,5])
#print(empty_arr)
print(d)

[[[1.03082189 1.93915573 1.25683772 1.0571346  1.38770822]
  [1.35709675 1.98638414 1.93959064 1.58277522 1.99310313]
  [1.9899145  1.86505637 1.16171823 1.36849024 1.30672666]]

 [[1.34086324 1.29047775 1.63786407 1.050654   1.93518431]
  [1.02584484 1.53163905 1.07160379 1.69149444 1.11708751]
  [1.19351251 1.9123815  1.31071241 1.3156425  1.80703011]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [143]:
d.shape  == f.shape

True

In [181]:
#f[d>1.5] = 1


In [154]:
d_max

1.9931031337764242

In [153]:
d

array([[[1.03082189, 1.93915573, 1.25683772, 1.0571346 , 1.38770822],
        [1.35709675, 1.98638414, 1.93959064, 1.58277522, 1.99310313],
        [1.9899145 , 1.86505637, 1.16171823, 1.36849024, 1.30672666]],

       [[1.34086324, 1.29047775, 1.63786407, 1.050654  , 1.93518431],
        [1.02584484, 1.53163905, 1.07160379, 1.69149444, 1.11708751],
        [1.19351251, 1.9123815 , 1.31071241, 1.3156425 , 1.80703011]]])

In [189]:
f[d == d_max] =100
f[(d>d_min ) & (d<d_mean )] =25
f[(d<d_max) & (d>d_mean)] = 75
f[d == d_mean] = 50
#f[d == d_min] = 0
f

array([[['25', '75', '25', '25', '25'],
        ['25', '75', '75', '75', '100'],
        ['75', '75', '25', '25', '25']],

       [['25', '25', '75', '25', '75'],
        ['A', '75', '25', '75', '25'],
        ['25', '75', '25', '25', '75']]], dtype='<U32')

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [188]:
f

array([[['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'D', 'D', 'E'],
        ['D', 'D', 'B', 'B', 'B']],

       [['B', 'B', 'D', 'B', 'D'],
        ['A', 'D', 'B', 'D', 'B'],
        ['B', 'D', 'B', 'B', 'D']]], dtype='<U32')

In [187]:
# your code here
f = f.astype(str) #because of array object can have only one type of data.
f[d == d_max] ="E"
f[(d>d_min ) & (d<d_mean )] ="B"
f[(d<d_max) & (d>d_mean)] = "D"
f[d == d_mean] = "C"
f[d == d_min] = "A"
f

array([[['B', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'D', 'D', 'E'],
        ['D', 'D', 'B', 'B', 'B']],

       [['B', 'B', 'D', 'B', 'D'],
        ['A', 'D', 'B', 'D', 'B'],
        ['B', 'D', 'B', 'B', 'D']]], dtype='<U32')