# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print(np.__version__)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [5]:
# Method 1

In [6]:
# Method 2

In [7]:
# Method 3

#### 4. Print *a*.


In [8]:
a = np.random.random((2,3,5))
print(a)

[[[0.26202705 0.04134064 0.11028999 0.07702441 0.11975651]
  [0.2665198  0.75148832 0.0107599  0.43649109 0.17675614]
  [0.94279972 0.41533643 0.03646431 0.29399061 0.46543897]]

 [[0.67290708 0.35223358 0.36898636 0.54112638 0.08832899]
  [0.65976937 0.81492946 0.38398705 0.72448    0.98155842]
  [0.16889729 0.42685239 0.17833094 0.40985675 0.42786573]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [9]:
# your code here

#### 6. Print *b*.


In [10]:
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
if a.size == b.size:
    print(True)
else:
    print(False)

# They do have the same size

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
 c = a + b

 # I'm not able to do this because the shapes of the array is different from each other.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [13]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
d = a + c
print(d)

# It works now because both arrays have the same shape

[[[1.26202705 1.04134064 1.11028999 1.07702441 1.11975651]
  [1.2665198  1.75148832 1.0107599  1.43649109 1.17675614]
  [1.94279972 1.41533643 1.03646431 1.29399061 1.46543897]]

 [[1.67290708 1.35223358 1.36898636 1.54112638 1.08832899]
  [1.65976937 1.81492946 1.38398705 1.72448    1.98155842]
  [1.16889729 1.42685239 1.17833094 1.40985675 1.42786573]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
print(a)
print(d)

# D is just always 1 higher than a in every entry. Because we have added a "one" matrix to it.

[[[0.26202705 0.04134064 0.11028999 0.07702441 0.11975651]
  [0.2665198  0.75148832 0.0107599  0.43649109 0.17675614]
  [0.94279972 0.41533643 0.03646431 0.29399061 0.46543897]]

 [[0.67290708 0.35223358 0.36898636 0.54112638 0.08832899]
  [0.65976937 0.81492946 0.38398705 0.72448    0.98155842]
  [0.16889729 0.42685239 0.17833094 0.40985675 0.42786573]]]
[[[1.26202705 1.04134064 1.11028999 1.07702441 1.11975651]
  [1.2665198  1.75148832 1.0107599  1.43649109 1.17675614]
  [1.94279972 1.41533643 1.03646431 1.29399061 1.46543897]]

 [[1.67290708 1.35223358 1.36898636 1.54112638 1.08832899]
  [1.65976937 1.81492946 1.38398705 1.72448    1.98155842]
  [1.16889729 1.42685239 1.17833094 1.40985675 1.42786573]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
e = np.multiply(a, c)
print(e)

[[[0.26202705 0.04134064 0.11028999 0.07702441 0.11975651]
  [0.2665198  0.75148832 0.0107599  0.43649109 0.17675614]
  [0.94279972 0.41533643 0.03646431 0.29399061 0.46543897]]

 [[0.67290708 0.35223358 0.36898636 0.54112638 0.08832899]
  [0.65976937 0.81492946 0.38398705 0.72448    0.98155842]
  [0.16889729 0.42685239 0.17833094 0.40985675 0.42786573]]]


#### 13. Does *e* equal to *a*? Why or why not?
e

In [17]:
print(e==a)

# It does equal a completly.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [18]:
d_max = np.max(e)
d_min = np.min(e)
d_mean = np.mean(e)
print(d_max, d_min, d_mean)

0.9815584176422847 0.010759902510686925 0.3868864551974538


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [19]:
f = np.empty((2,3,5))
print(f)

[[[0.26202705 0.04134064 0.11028999 0.07702441 0.11975651]
  [0.2665198  0.75148832 0.0107599  0.43649109 0.17675614]
  [0.94279972 0.41533643 0.03646431 0.29399061 0.46543897]]

 [[0.67290708 0.35223358 0.36898636 0.54112638 0.08832899]
  [0.65976937 0.81492946 0.38398705 0.72448    0.98155842]
  [0.16889729 0.42685239 0.17833094 0.40985675 0.42786573]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [36]:
f[(f>d_min) & (f<d_mean)] = 25
f[(f>d_mean) & (f<d_max)] = 75
f[f == d_mean] = 50
f[f == d_min] = 0
f[f == d_max] = 100
print(f)

[[[ 25.  25.  25.  25.  25.]
  [ 25.  75.   0.  75.  25.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  75.  25.  75. 100.]
  [ 25.  75.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [39]:
f[(str(f)>str(d_min)) & (str(int((f)))<str(int(d_mean)))] = "A"
f[(f>d_mean) & (f<d_max)] = "B"
f[f == d_mean] = "C"
f[f == d_min] = "D"
f[f == d_max] = "E"

# Somehow have to convert the float to string first. Somehow. hm.

TypeError: only size-1 arrays can be converted to Python scalars