# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.__version__

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
np.random.seed(12)
a = np.random.random([2,3,5])
print(a)

[[[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
  [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
  [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]]

 [[0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]
  [0.76456045 0.0208098  0.13521018 0.11627302 0.30989758]
  [0.67145265 0.47122978 0.8161683  0.28958678 0.73312598]]]


In [4]:
np.random.seed(9)
a = np.random.normal(size=(2,3,5))
print(a)

[[[ 1.10855471e-03 -2.89544069e-01 -1.11606630e+00 -1.28827567e-02
   -3.78361464e-01]
  [-4.81135363e-01 -1.51733118e+00 -4.90871981e-01 -2.40680579e-01
   -6.47947460e-01]
  [ 6.35891080e-01  1.74011731e+00  2.96682218e-01  7.07503662e-01
    1.82281576e+00]]

 [[ 4.30769029e-01  1.54272963e+00 -9.00721171e-01 -1.37125010e-01
    1.29757901e+00]
  [ 6.75271167e-01  3.19581170e-02  9.18145896e-01  3.80509466e-01
    5.16367487e-01]
  [-3.55239458e-01  2.08777001e-01  3.28411076e-01 -4.98224766e-01
   -2.09177677e+00]]]


In [5]:
a = np.random.exponential(size=(2,3,5))
print(a)

[[[0.94298831 0.68573813 0.65003791 0.57191315 2.04336651]
  [0.20746541 1.16370806 1.21580646 2.59293843 0.04025426]
  [1.04161791 1.01626021 0.61933491 0.05451894 0.03933448]]

 [[0.18576518 1.5825423  0.17746065 0.14935734 0.43528064]
  [0.66261498 1.19645575 1.61523685 0.31030182 2.40214258]
  [0.02313245 0.47020007 0.22268532 0.41977485 0.58718897]]]


#### 4. Print *a*.


In [6]:
print(a)

[[[0.94298831 0.68573813 0.65003791 0.57191315 2.04336651]
  [0.20746541 1.16370806 1.21580646 2.59293843 0.04025426]
  [1.04161791 1.01626021 0.61933491 0.05451894 0.03933448]]

 [[0.18576518 1.5825423  0.17746065 0.14935734 0.43528064]
  [0.66261498 1.19645575 1.61523685 0.31030182 2.40214258]
  [0.02313245 0.47020007 0.22268532 0.41977485 0.58718897]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
b = np.random.randint(1,2, (5,2,3))


#### 6. Print *b*.


In [8]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
absum = np.sum(a, b)
print(absum)
# They can't be added because they have different shapes.

TypeError: only integer scalar arrays can be converted to a scalar index

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [11]:
import numpy as np
c = b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print("A is: ",a)
print("D is: ",d)


A is:  [[[0.94298831 0.68573813 0.65003791 0.57191315 2.04336651]
  [0.20746541 1.16370806 1.21580646 2.59293843 0.04025426]
  [1.04161791 1.01626021 0.61933491 0.05451894 0.03933448]]

 [[0.18576518 1.5825423  0.17746065 0.14935734 0.43528064]
  [0.66261498 1.19645575 1.61523685 0.31030182 2.40214258]
  [0.02313245 0.47020007 0.22268532 0.41977485 0.58718897]]]
D is:  [[[1.94298831 1.68573813 1.65003791 1.57191315 3.04336651]
  [1.20746541 2.16370806 2.21580646 3.59293843 1.04025426]
  [2.04161791 2.01626021 1.61933491 1.05451894 1.03933448]]

 [[1.18576518 2.5825423  1.17746065 1.14935734 1.43528064]
  [1.66261498 2.19645575 2.61523685 1.31030182 3.40214258]
  [1.02313245 1.47020007 1.22268532 1.41977485 1.58718897]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = np.multiply(a,c)
print(e)

[[[0.94298831 0.68573813 0.65003791 0.57191315 2.04336651]
  [0.20746541 1.16370806 1.21580646 2.59293843 0.04025426]
  [1.04161791 1.01626021 0.61933491 0.05451894 0.03933448]]

 [[0.18576518 1.5825423  0.17746065 0.14935734 0.43528064]
  [0.66261498 1.19645575 1.61523685 0.31030182 2.40214258]
  [0.02313245 0.47020007 0.22268532 0.41977485 0.58718897]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
e == a
# Yes, e is equal to a because c is an array formed by only ones, 
# and mutiplying by one gives the same number.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = np.mean(d)
print(d_mean)

3.5929384270384346
1.0231324539898956
1.7775140938241911


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
f = np.empty((2,3,5))
print(f)

[[[0.94298831 0.68573813 0.65003791 0.57191315 2.04336651]
  [0.20746541 1.16370806 1.21580646 2.59293843 0.04025426]
  [1.04161791 1.01626021 0.61933491 0.05451894 0.03933448]]

 [[0.18576518 1.5825423  0.17746065 0.14935734 0.43528064]
  [0.66261498 1.19645575 1.61523685 0.31030182 2.40214258]
  [0.02313245 0.47020007 0.22268532 0.41977485 0.58718897]]]


## 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# print(d)
# f = []
# for i in d:
#     for i2 in i:
#         for i3 in i2:
#             if i3 > d_min and i3 < d_mean:
#                 i
#             elif i3 > d_mean and i3 < d_max

f[(d>d_min)&(d<d_mean)] = 25
f[(d>d_mean)&(d<d_max)] = 75
f[d==d_mean] = 50
f[d==d_min] = 0
f[d==d_max] = 100
print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 25.  75.  75. 100.  25.]
  [ 75.  75.  25.  25.  25.]]

 [[ 25.  75.  25.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [  0.  25.  25.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
print(d)
print(f)

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here