# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [3]:
a = np.empty((2,3,5))
a

array([[[-2.00000000e+000, -2.00000000e+000,  7.41098469e-323,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000, -2.00000000e+000, -2.00000000e+000,
          3.45845952e-323,  0.00000000e+000],
        [-2.00000000e+000,  1.29074410e-231,  2.47032823e-323,
          0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          2.12199579e-314,  2.08600886e-308]]])

In [4]:
a = np.random.random((2,3,5))
a

array([[[0.48604051, 0.0419424 , 0.41106001, 0.4602018 , 0.40628637],
        [0.07747816, 0.45324657, 0.67968013, 0.27027494, 0.64690626],
        [0.42668067, 0.53456701, 0.27812947, 0.98459158, 0.76691513]],

       [[0.69233294, 0.41754213, 0.91526892, 0.67154342, 0.74168486],
        [0.40367198, 0.2140727 , 0.2620346 , 0.56414129, 0.61066082],
        [0.30300874, 0.85528073, 0.18928417, 0.01942086, 0.62004734]]])

In [5]:
a = np.random.randint(0, 100, (2,3,5))
a

array([[[ 5, 14, 78, 27, 42],
        [65, 21, 34, 27, 43],
        [74, 81, 64, 67, 46]],

       [[45, 69, 70, 93, 12],
        [52, 45,  1, 77, 25],
        [89, 97, 76, 34, 10]]])

#### 4. Print *a*.


In [6]:
print(a)

[[[ 5 14 78 27 42]
  [65 21 34 27 43]
  [74 81 64 67 46]]

 [[45 69 70 93 12]
  [52 45  1 77 25]
  [89 97 76 34 10]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]
```

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
np.size(a) == np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


Adding them in a formula is not possible as they are two different arrays.. 
Only ways to so it is to add the sum of each np array together:

In [10]:
sum_a_b = np.sum(a) + np.sum(a)
sum_a_b

2966

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [11]:
c = np.reshape(b,(5,3,2))
c = np.transpose(c)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c
d

array([[[ 6., 15., 79., 28., 43.],
        [66., 22., 35., 28., 44.],
        [75., 82., 65., 68., 47.]],

       [[46., 70., 71., 94., 13.],
        [53., 46.,  2., 78., 26.],
        [90., 98., 77., 35., 11.]]])

it works since the shape of the arrays is the same..

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)
print()
print(d)

[[[ 5 14 78 27 42]
  [65 21 34 27 43]
  [74 81 64 67 46]]

 [[45 69 70 93 12]
  [52 45  1 77 25]
  [89 97 76 34 10]]]

[[[ 6. 15. 79. 28. 43.]
  [66. 22. 35. 28. 44.]
  [75. 82. 65. 68. 47.]]

 [[46. 70. 71. 94. 13.]
  [53. 46.  2. 78. 26.]
  [90. 98. 77. 35. 11.]]]


Float vs. int > array d is a float since a was summed with a float array 

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
e

array([[[ 5., 14., 78., 27., 42.],
        [65., 21., 34., 27., 43.],
        [74., 81., 64., 67., 46.]],

       [[45., 69., 70., 93., 12.],
        [52., 45.,  1., 77., 25.],
        [89., 97., 76., 34., 10.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

yes, since e is a * 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)
print("mean is: ", np.mean(d))
print("max value is: ", np.max(d))
print("min value is: ", np.min(d))

mean is:  50.43333333333333
max value is:  98.0
min value is:  2.0


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
f = np.zeros((2,3,5))
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [31]:
f[(d < d_max) & (d > d_mean)] = 75
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_max] = 100
f[d == d_min] = 0
f[d == d_mean] = 50

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [33]:
print(d)
print()
print(f)

[[[ 6. 15. 79. 28. 43.]
  [66. 22. 35. 28. 44.]
  [75. 82. 65. 68. 47.]]

 [[46. 70. 71. 94. 13.]
  [53. 46.  2. 78. 26.]
  [90. 98. 77. 35. 11.]]]

[[[ 25.  25.  75.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  75.  75.  75.  25.]
  [ 75.  25.   0.  75.  25.]
  [ 75. 100.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [34]:
f = f.astype(str)
f[(d < d_max) & (d > d_mean)] = "D"
f[(d > d_min) & (d < d_mean)] = "B"
f[d == d_max] = "E"
f[d == d_min] = "A"
f[d == d_mean] = "C"

f

array([[['B', 'B', 'D', 'B', 'B'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'B']],

       [['B', 'D', 'D', 'D', 'B'],
        ['D', 'B', 'A', 'D', 'B'],
        ['D', 'E', 'D', 'B', 'B']]], dtype='<U32')