# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [10]:
# Method 1
np.random.rand(2,3,5)

array([[[0.56076709, 0.51478387, 0.09671303, 0.36496286, 0.435285  ],
        [0.23167623, 0.65291323, 0.70990587, 0.63400745, 0.81421025],
        [0.96210154, 0.82279647, 0.84607155, 0.65793221, 0.75367217]],

       [[0.86514618, 0.80060431, 0.42600299, 0.22344455, 0.69479021],
        [0.79511542, 0.55929343, 0.10455721, 0.41746293, 0.77407291],
        [0.03040166, 0.68829047, 0.42912848, 0.52964653, 0.4894555 ]]])

In [24]:
# Method 2
np.random.randint(5, size=(2,3,5))

array([[[1, 4, 1, 1, 0],
        [0, 4, 2, 2, 3],
        [1, 3, 4, 4, 3]],

       [[4, 2, 1, 4, 2],
        [4, 4, 1, 3, 2],
        [4, 3, 4, 4, 4]]])

In [26]:
# Method 3
a = np.arange(30).reshape(2,3,5)

#### 4. Print *a*.


In [27]:
# your code here
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [18]:
# your code here
b = np.full((5,3,2),1.)


#### 6. Print *b*.


In [19]:
# your code here
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [29]:
# your code here
print(a.size)
print(b.size)

#yes

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [32]:
# your answer here



#no need to be the same structure

numpy.ndarray

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [37]:
# your code here
np.transpose(b).shape

c = np.transpose(b)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
# your code/answer here
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
# your code/answer here
print(a)

print(d)

#a starts with 0 , d starts with 1 , values are added for d (a+b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]
  [11. 12. 13. 14. 15.]]

 [[16. 17. 18. 19. 20.]
  [21. 22. 23. 24. 25.]
  [26. 27. 28. 29. 30.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
# your code/answer here
print(e)
print(a)

#yes 

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]]

 [[15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [56]:
# your code here
f = np.zeros((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
# your code here
for elem in d:
    if elem > d_min and elem < d_mean:
        f.append('15')
    elif elem > d_mean and elem < d_max:
        f.append('75')
    elif elem = d_mean:
        f.append('50')
    elif elem = d_min:
        f.append('0')
    elif elem = d_max:
        f.append('100')
    else:
        f.append('0')

SyntaxError: invalid syntax (<ipython-input-58-6cadccc59c5e>, line 7)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here
print(d)
print(f)

#yes

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here