# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [8]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [9]:
# your code here

np.__version__

'1.20.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
**Hint**: look for `np.random` and search for functions you want to use.

The outcomes should look like:
```python
array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])
```
*The values do not need to be the same. Remember that you are creating random numbers.*

In [25]:
# Method 1
# Generating random floating point numbers between 0 and 1, but all values have the same probability to appear
# *NOTE --> I'm going to use this array of numbers for the next exercises


np.random.seed(10)
a = np.random.random((2,3,5))
print(a)

[[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
  [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
  [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]]

 [[0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
  [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
  [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]]]


In [11]:
# Method 2
# Generating a 3 dimensional array (2x3x5) of normal distrubution with mean=5 and stdv=3

np.random.seed(10)
a = np.random.normal(5,3,size=(2,3,5))
print(a)

[[[ 8.99475951  7.14583692  0.36379912  4.97484845  6.86400792]
  [ 2.83974332  5.79653476  5.32564558  5.01287429  4.47619937]
  [ 6.29907857  8.60911212  2.10480299  8.08482223  5.68589039]]

 [[ 6.33541284  1.59019336  5.40541064  9.45361101  1.76058534]
  [-0.93318484 -0.23011689  5.79821049 12.15490199  8.37107376]
  [10.01786664  5.29744765  9.19398913  4.18625604  6.83961255]]]


In [12]:
# Method 3
# Generating random 3 dimensional (2x3x5) array of integeres betwenn 0 and 10


np.random.seed(10)
a = np.random.randint(0, 11, (2,3,5))
print(a)

[[[ 9  4  0  1  9]
  [ 0  1 10  8  9]
  [ 0 10  8  6  4]]

 [[ 3  0  4  6  8]
  [10  1  8  4  1]
  [ 3  6  5  3  9]]]


#### 4. Print *a*.


In [26]:
# your code here
print(a)

[[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
  [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
  [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]]

 [[0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
  [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
  [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]]]


#### 5. Create a 5x3x2 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

The outcome should look like:
```python
       [[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]]
```

In [27]:
# your code here

b = np.ones((5,3,2))

#### 6. Print *b*.


In [28]:
# your code here

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [29]:
# your code here

print('a size:', a.shape)
print('b size:', b.shape)

a size: (2, 3, 5)
b size: (5, 3, 2)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [30]:
# your answer here

ab = np.add(a,b)

# No, because they have different shape/size. 


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

**Hint**: search for `np.transpose`

In [35]:
# your code here

c = np.transpose(b)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here

d = np.add(a,c)

print(d)

# It works, because now we have two arrays with the same size = 2x3x5 

[[[1.77132064 1.02075195 1.63364823 1.74880388 1.49850701]
  [1.22479665 1.19806286 1.76053071 1.16911084 1.08833981]
  [1.68535982 1.95339335 1.00394827 1.51219226 1.81262096]]

 [[1.61252607 1.72175532 1.29187607 1.91777412 1.71457578]
  [1.54254437 1.14217005 1.37334076 1.67413362 1.44183317]
  [1.43401399 1.61776698 1.51313824 1.65039718 1.60103895]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here

print('a', a)
print('############################################################')
print('d', d)

# We added each value of a to each value of c. 
# This is possible because the two arrays have absolutely the same structure (2x3x5) 


a [[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
  [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
  [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]]

 [[0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
  [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
  [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]]]
############################################################
d [[[1.77132064 1.02075195 1.63364823 1.74880388 1.49850701]
  [1.22479665 1.19806286 1.76053071 1.16911084 1.08833981]
  [1.68535982 1.95339335 1.00394827 1.51219226 1.81262096]]

 [[1.61252607 1.72175532 1.29187607 1.91777412 1.71457578]
  [1.54254437 1.14217005 1.37334076 1.67413362 1.44183317]
  [1.43401399 1.61776698 1.51313824 1.65039718 1.60103895]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [38]:
# your code here

e = np.multiply(a,c)

print(e)

[[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
  [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
  [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]]

 [[0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
  [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
  [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
# your code/answer here

is_a_equal_to_e = a == e
is_a_equal_to_e

# Yes, because when we multiply x by 1, we get x 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f'''max value of d is: {d_max}
min value of d is: {d_min}
mean of d is: {d_mean}''')

max value of d is: 1.9533933461949364
min value of d is: 1.0039482663279145
mean of d is: 1.511009064157907


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.zeros`.


In [44]:
# your code here

f = np.zeros((2,3,5))
f


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [53]:
# your code here

#for index in range(len(d)):
#    if d[index] > d_min and (d[index] < d_mean):
#        f[index] = 25


f = np.where( ( d > d_min ) & ( d < d_mean ), 25, f )
f = np.where( ( d > d_mean ) & ( d < d_max ), 75, f )
f = np.where( ( d == d_mean ), 50, f )
f = np.where( ( d == d_min ), 0, f )
f = np.where( ( d == d_max ), 100, f)




In [54]:
f

array([[[ 75.,  25.,  75.,  75.,  25.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 75., 100.,   0.,  75.,  75.]],

       [[ 75.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [57]:
# your code here

print(d)
print()
print()
print(f)

[[[1.77132064 1.02075195 1.63364823 1.74880388 1.49850701]
  [1.22479665 1.19806286 1.76053071 1.16911084 1.08833981]
  [1.68535982 1.95339335 1.00394827 1.51219226 1.81262096]]

 [[1.61252607 1.72175532 1.29187607 1.91777412 1.71457578]
  [1.54254437 1.14217005 1.37334076 1.67413362 1.44183317]
  [1.43401399 1.61776698 1.51313824 1.65039718 1.60103895]]]


[[[ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  25.  25.]
  [ 75. 100.   0.  75.  75.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here